version: '3.1'

services:
    web:
      image: rogfk/nam-multiauth-select
      ports: 
        - 10000:80
      deploy:
        placement:
          constraints:
            - node.role == worker
        replicas: 3
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
          window: 120s